FROM openjdk:21-jdk-slim AS deps
WORKDIR /app
COPY pom.xml /app
COPY .mvn .mvn
COPY ./mvnw ./mvnw
RUN ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

FROM openjdk:21-jdk-slim AS builder
WORKDIR /app
COPY --from=deps /root/.m2/repository /root/.m2/repository
COPY . /app/
RUN chmod +x /app/docker-entrypoint.sh
COPY pom.xml .
COPY .mvn .mvn
COPY ./mvnw ./mvnw

ENTRYPOINT ["/app/docker-entrypoint.sh"]
