spring:
  profiles.active: ${SPRING_ACTIVE_PROFILE:default}
  application:
    name: moviee
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      jdb:
        time_zone: UTC
  
  flyway:
    baseline-on-migrate: true
server:
  port: 8080
logging:
  level:
    com.codemages: debug