spring:
  profiles.active: ${SPRING_ACTIVE_PROFILE:default}
  application:
    name: moviee
logging.level.org.springframework:
  web: DEBUG
  security: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
server:
  port: 8080